alias lol="clear && ls"
alias ...="cd .."
alias …="cd .."
alias x="cd ~/x/"
alias github="cd ~/x/Github"
alias 0="cd ~"
alias todo="cd ~/x/TODO"
alias juno="sh ~/.juno.sh"
alias cmds="clear && echo bashrc && cat ~/.bashrc"
alias gitsync="python /data/data/com.termux/files/home/x/Github/.gitsync.py"
# hey dont use this as a todo update button right?
alias todou="cd /data/data/com.termux/files/home/x/TODO && git pull"
